---
# tasks file for wordpress
  - name: Baixar Wordpress
    get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/tmp/wordpress.tar.gz
    become: yes

  - name: Extrair pacote Wordpress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www
    become: yes

  - name: Copiar/Criar arquivo wpconfig
    command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

  - name: Atualizar arquivo wpconfig 
    lineinfile:
      dest=/var/www/wordpress/wp-config.php
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
    with_items:
      - { 'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{mysql_banco}}');"
      - { 'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{mysql_usario}}');"
      - { 'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{mysql_senha}}');"
    become: yes
    
  - name: Mudar proprietario da pasta wordpress
    file: path=/var/www/wordpress/ owner=www-data group=www-data state=directory recursive=yes

  - name: Iniciar PHP
    service: name=php-fpm state=started enabled=yes

  - name: Reiniciar nginx
    service: name=nginx state=restarted enabled=yes
